name: Build & Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 8.1.0
      uses: actions/setup-node@v1
      with:
        node-version: '8.1.0'
    - run: npm install
    - run: npm build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifact-${{ github.sha }}
        path: artifacts/${{ github.sha }}
